/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cm5w1PRR7k7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useState } from "react"
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card"
import Image from 'next/image';

export function MusicDisplay() {
  const [isOpen1, setIsOpen1] = useState(false)
  const [isOpen2, setIsOpen2] = useState(false)
  const [isOpen3, setIsOpen3] = useState(false)
  const [isOpen4, setIsOpen4] = useState(false)

  return (
    <div className="w-full mt-3 mx-auto">
      <div className="grid gap-2">
        <div className="flex items-center gap-2">
          <div className="flex-shrink-0">
            <Image
              src="/AllenStevenson.webp"
              alt="Song Cover"
              width={40}
              height={40}
              className="rounded-md"
              style={{ aspectRatio: "1", objectFit: "cover" }}
            />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-medium truncate">Fortiter et Recte</h3>
            <p className="text-sm text-muted-foreground truncate">
              2023 <span className="hidden md:inline" >| Premiere: Atlantic Music Festival</span> {" "}
              <HoverCard open={isOpen1} onOpenChange={setIsOpen1}>
                <HoverCardTrigger asChild>
                  <button 
                    className="cursor-pointer bg-transparent border-none p-0 inline-flex items-center underline underline-offset-2"
                    onMouseEnter={() => setIsOpen1(true)}
                    onMouseLeave={() => setIsOpen1(false)}
                  >
                    
                    <InfoIcon 
                      className="w-4 h-4 ml-1" 
                      onMouseEnter={() => setIsOpen1(true)} 
                      onMouseLeave={() => setIsOpen1(false)} 
                    />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80">
                 <div className="flex flex-col space-y-3 text-wrap">
                    <h4 className="text-lg font-semibold">Premiere Information</h4>
                    <div className="flex items-center space-x-2 text-gray-500">
                      <CalendarIcon className="w-4 h-4" />
                      <span>July 29th, 2023</span>
                    </div>
                    <p className="text-sm">The piece was performed at the Atlantic Music Festival. It is dedicated to David Trower.</p>
                    <ul className="text-sm list-disc pl-5 space-y-1">
                      <li>Don Qiao, Violin I</li>
                      <li className="break-words">Yohali Montero, Violin II</li>
                      <li className="break-words">Chihiro Tanaka, Viola</li>
                      <li className="break-words">Jameson Platte, Cello</li>
                    </ul>
                  </div>
                </HoverCardContent>
              </HoverCard>
            </p>
          </div>
          <Link
            href="https://youtu.be/Y50GgIGvjTE?si=FGd2B6kkHUFV-8pP"
            target="_blank"
            className="inline-flex items-center justify-center bg-primary text-primary-foreground rounded-md px-3 py-1 text-xs font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            <PlayIcon className="w-4 h-4 mr-1" />
            Play
          </Link>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex-shrink-0">
            <Image
              src="/music/WQXR.png"
              alt="Song Cover"
              width={40}
              height={40}
              className="rounded-md"
              style={{ aspectRatio: "1", objectFit: "cover" }}
            />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-medium truncate">Peace Interrupted</h3>
            <p className="text-sm text-muted-foreground truncate">
              2022 <span className="hidden md:inline" >| Premiere: WQXR Features NYPhil VYC</span> {" "}
              <HoverCard open={isOpen3} onOpenChange={setIsOpen3}>
                <HoverCardTrigger asChild>
                  <button 
                    className="cursor-pointer bg-transparent border-none p-0 inline-flex items-center underline underline-offset-2"
                    onMouseEnter={() => setIsOpen3(true)}
                    onMouseLeave={() => setIsOpen3(false)}
                  >
                    <InfoIcon 
                      className="w-4 h-4 ml-1" 
                      onMouseEnter={() => setIsOpen3(true)} 
                      onMouseLeave={() => setIsOpen3(false)} 
                    />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80">
                  <div className="flex flex-col space-y-3 text-wrap">
                    <h4 className="text-lg font-semibold">Premiere Information</h4>
                    <div className="flex items-center space-x-2 text-gray-500">
                      <CalendarIcon className="w-4 h-4" />
                      <span>June 15, 2022</span>
                    </div>
                    <p className="text-sm">The piece was performed by O Kwarteto, an incredible string quartet from New York City.</p>
                  </div>
                </HoverCardContent>
              </HoverCard>
            </p>
          </div>
          <Link
            href="https://www.wnyc.org/widgets/ondemand_player/wqxr/#file=https://chrt.fm/track/53A61E/pdst.fm/e/www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/wqxr/wqxr042022_vyc_nicholas_hutfilz.mp3&share=0"
            target="_blank"
            className="inline-flex items-center justify-center bg-primary text-primary-foreground rounded-md px-3 py-1 text-xs font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            <PlayIcon className="w-4 h-4 mr-1" />
            Play
          </Link>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex-shrink-0">
            <Image
              src="/music/FlightoftheMango.png"
              alt="Song Cover"
              width={40}
              height={40}
              className="rounded-md"
              style={{ aspectRatio: "1", objectFit: "cover" }}
            />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-medium truncate">Flight of the Mango</h3>
            <p className="text-sm text-muted-foreground truncate">
              2021 <span className="hidden md:inline" >| Premiere: WQXR Features NYPhil VYC</span>{" "}
              <HoverCard open={isOpen4} onOpenChange={setIsOpen4}>
                <HoverCardTrigger asChild>
                  <button 
                    className="cursor-pointer bg-transparent border-none p-0 inline-flex items-center underline underline-offset-2"
                    onMouseEnter={() => setIsOpen4(true)}
                    onMouseLeave={() => setIsOpen4(false)}
                  >
                    <InfoIcon 
                      className="w-4 h-4 ml-1" 
                      onMouseEnter={() => setIsOpen4(true)} 
                      onMouseLeave={() => setIsOpen4(false)} 
                    />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80">
                <div className="flex flex-col space-y-3 text-wrap">
                    <h4 className="text-lg font-semibold">Premiere Information</h4>
                    <div className="flex items-center space-x-2 text-gray-500">
                      <CalendarIcon className="w-4 h-4" />
                      <span>September 23, 2021</span>
                    </div>
                    <p className="text-sm">The piece was performed by members of the New York Philharmonic as well as artists from WQXR's Artist Propulsion Lab:</p>
                    <ul className="text-sm list-disc pl-5 space-y-1">
                      <li>Kara Dugan, mezzo-soprano (Artist Propulsion Lab)</li>
                      <li>Mindy Kaufman, flute (New York Philharmonic)</li>
                      <li className="break-words">Leelanee Sterrett, french horn (New York Philharmonic)</li>
                      <li className="break-words">Jordan Bak, viola (Artist Propulsion Lab)</li>
                      <li className="break-words">Max Zeugner, contrabass (New York Philharmonic)</li>
                    </ul>
                  </div>
                </HoverCardContent>
              </HoverCard>
            </p>
          </div>
          <Link
            href="https://youtu.be/KQuoenpzdaA?si=7Eg1AKQOAyX7njVC"
            target="_blank"
            className="inline-flex items-center justify-center bg-primary text-primary-foreground rounded-md px-3 py-1 text-xs font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            <PlayIcon className="w-4 h-4 mr-1" />
            Play
          </Link>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex-shrink-0">
            <Image
              src="/music/MountainEchoes.webp"
              alt="Mountain Echoes Cover"
              width={40}
              height={40}
              className="rounded-md"
              style={{ aspectRatio: "1", objectFit: "cover" }}
            />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-medium truncate">Mountain Echoes</h3>
            <p className="text-sm text-muted-foreground truncate">
              2020 <span className="hidden md:inline" >| Premiere: Very Young Composers Program</span> {" "}
              <HoverCard open={isOpen2} onOpenChange={setIsOpen2}>
                <HoverCardTrigger asChild>
                  <button 
                    className="cursor-pointer bg-transparent border-none p-0 inline-flex items-center underline underline-offset-2"
                    onMouseEnter={() => setIsOpen2(true)}
                    onMouseLeave={() => setIsOpen2(false)}
                  >
                    <InfoIcon 
                      className="w-4 h-4 ml-1" 
                      onMouseEnter={() => setIsOpen2(true)} 
                      onMouseLeave={() => setIsOpen2(false)} 
                    />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80">
                  <div className="flex flex-col space-y-3 text-wrap">
                    <h4 className="text-lg font-semibold">Premiere Information</h4>
                    <div className="flex items-center space-x-2 text-gray-500">
                      <CalendarIcon className="w-4 h-4" />
                      <span>2020</span>
                    </div>
                    <p className="text-sm">The piece was performed at the Very Young Composers Program.</p>
                  </div>
                </HoverCardContent>
              </HoverCard>
            </p>
          </div>
          <Link
            href="https://youtu.be/WhotD2CbS9E?si=v50Kmut5ksJwDcO1"
            target="_blank"
            className="inline-flex items-center justify-center bg-primary text-primary-foreground rounded-md px-3 py-1 text-xs font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            <PlayIcon className="w-4 h-4 mr-1" />
            Play
          </Link>
        </div>
      </div>
      <div className="mt-4 w-full">
        <Button variant="outline" asChild className="w-full">
          <Link href="https://open.spotify.com/artist/5tNOOAXIEIY7r82SXcoBpm?si=eBApjA5TRq-LErCIZ07-jQ" target="_blank" rel="noopener noreferrer" className="w-full">
            View more on Spotify
          </Link>
        </Button>
      </div>
    </div>
  )
}

function PlayIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}

function InfoIcon(props: React.SVGProps<SVGSVGElement>) { // Specify the type for props
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}

function CalendarIcon(props: React.SVGProps<SVGSVGElement>) { // Specify the type for props
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
      <line x1="16" y1="2" x2="16" y2="6" />
      <line x1="8" y1="2" x2="8" y2="6" />
      <line x1="3" y1="10" x2="21" y2="10" />
    </svg>
  )
}